-- sample_data.sql
INSERT INTO TAXPAYERS (TAXPAYER_ID, NAME, ID_NUMBER, EMAIL, PHONE, ADDRESS)
VALUES ('TP-0001', 'Acme Corp', 'PIN123456', 'finance@acme.example', '+254700000001', 'Nairobi');

INSERT INTO TAXPAYERS (TAXPAYER_ID, NAME, ID_NUMBER, EMAIL, PHONE, ADDRESS)
VALUES ('TP-0002', 'Jane Doe', 'ID987654', 'jane.doe@example.com', '+254700000002', 'Nairobi');

INSERT INTO REGISTRATION_LOGS (TAXPAYER_ID, ACTION, DETAILS)
VALUES ('TP-0001', 'REGISTER', 'Initial registration for Acme Corp');

INSERT INTO PAYMENTS (PAYMENT_ID, TAXPAYER_ID, AMOUNT, METHOD, STATUS, RECEIPT_NUMBER)
VALUES ('PAY-1001', 'TP-0001', 1500.00, 'card', 'SUCCESS', 'RCPT-1001');

COMMIT;